defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  3b31166f-6db9-429f-8ed6-0c2c66424a07: # Kevin Am√©zaga
    enabledByDefault: true
    hasUrls: true
    template: about
    uriFormat: about
type: single
